# Development project infrastructure generated over the Docker
version: "3.7"

services:
  # MariaDB
  db:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./env/mysql.env

  # Nginx
  server:
    build:
      context: ./docker/nginx
    links:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ../:/app
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf

  # PHP-FPM with WP dependencies
  wordpress:
    build:
      context: ./docker/wp-fpm
    volumes:
      - ../:/app
      - ./xdebug/profiler:/tmp/xdebug_profiler
      - ./xdebug/trace:/tmp/xdebug_trace
    env_file:
      - ./env/app.env
      - ./env/xdebug.env
    depends_on:
      - db
      - smtp

  # WP CLI
  wp:
    build:
      context: ./docker/wp-cli
    depends_on:
      - db
      - smtp
    env_file:
      - ./env/app.env
      - ./env/xdebug.env
    volumes:
      - ../:/app
      - ./xdebug/profiler:/tmp/xdebug_profiler
      - ./xdebug/trace:/tmp/xdebug_trace

  # Node 8.2 with NPM/Yarn/npx
  assets-node:
    image: node:10
    volumes:
      - ../:/app
    working_dir: /app/assets

  # Composer
  inc-composer:
    image: composer
    volumes:
      - ../inc:/app
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache

  # Composer WP packages
  wp-composer:
    image: composer
    volumes:
      - ../wp-packages:/app
      - ../public:/public
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache

  # Composer CLI
  cli-composer:
    image: composer
    volumes:
      - ../cli:/app
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache

  # Composer CLI
  phpqa-composer:
    image: composer
    volumes:
      - ../phpqa:/app
      # Map local user Composer directory with container for cache packages
      - ~/.docker_cache/composer:/tmp/cache

  # PHPQA
  phpqa:
    image: jakzal/phpqa:alpine
    volumes:
      - ../:/app
      - ../phpqa/.tmp-phpqa:/tmp
    working_dir: /app/phpqa

  # Test SMTP server
  smtp:
    image: schickling/mailcatcher
    ports:
      - 1025
      - 1080:1080
    environment:
      MAILCATCHER_PORT: 1025

  # Deployer
  deployer:
    build:
      context: ./docker/deployer
      args:
        - PHP_VERSION=7
        - DEPLOYER_VERSION=latest
    volumes:
      - ../deploy:/deploy
      - ../deploy/.ssh:/root/.ssh

  # Xdebug profiling viewer
  webgrind:
    image: wodby/webgrind:1.5
    ports:
      - "8000:8080"
    volumes:
      - ./xdebug/profiler:/tmp
      - ../:/app

volumes:
  mysql_data:
    name: ${VOLUME_PREFIX}mysql_data
